FROM node:erbium

COPY /server /server
COPY /client /client

WORKDIR /client

RUN npm install
RUN npm run build

WORKDIR ../server
RUN npm install
RUN npm install express
RUN npm install morgan
RUN npm install natural
RUN npm install twitter
RUN npm install redis

EXPOSE 3000

CMD ["node", "index.js"]